name: CD Pipeline
on:
 push:
   branches: [ main ]
   paths:
     - 'infrastructure/**'
     - 'backend/**'
     - '.github/workflows/cd.yml'
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Azure Login
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
   - name: Install Bicep
     run: az bicep install
   - name: Deploy Infrastructure
     run: |
       cd infrastructure
       az deployment sub create --location eastus --template-file main.bicep --parameters parameters.json